---
- { become: yes, include: compat.yml }
- { become: yes, include: epel.yml, when: ansible_distribution == 'CentOS'}
- become: yes
  include: Debian.yml
  when: ansible_os_family in [ 'Debian', 'Linuxmint' ]
- { become: yes, include: install_package_names.yml }
